[package]
name = "serde-test"
version = "0.1.0"
authors = ["Daiju Nakayama <42.daiju@gmail.com>"]

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"
toml = "*"
serde-pickle = "*"
ron = "*"
rmp-serde = "*"
